mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^pjt_inventory/', include('pjt_inventory.urls')),
    url(r'^admin/', admin.site.urls),
]

pjt_inventory/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'pjt_inventory'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # List pjt_inventory/product_list
    url(r'^product_list', views.ProductListView.as_view(), name='product_list'),
    # List pjt_inventory/supplier_list
    url(r'^supplier_list', views.SupplierListView.as_view(), name='supplier_list'),
    # List pjt_inventory/brand_list
    url(r'^brand_list', views.BrandListView.as_view(), name='brand_list'),
    # List pjt_inventory/category_list
    url(r'^category_list', views.CategoryListView.as_view(), name='category_list'),
    # Details pjt_inventory/27/product_detail
    url(r'^(?P<pk>[0-9]+)/$', views.ProductDetailView.as_view(), name='product_detail'),
    # Details pjt_inventory/27/supplier_detail
    url(r'^(?P<pk>[0-9]+)/supplier_detail', views.SupplierDetailView.as_view(), name='supplier_detail'),
    # Details pjt_inventory/27/brand_detail
    url(r'^(?P<pk>[0-9]+)/brand_detail', views.BrandDetailView.as_view(), name='brand_detail'),
    # /pjt_inventory/product_add
    url(r'^product_add/$', views.ProductCreate.as_view(), name='product_add'),
    # /pjt_inventory/27/product_edit
    url(r'^(?P<pk>[0-9]+)/product_edit/$', views.ProductEdit.as_view(), name='product_edit'),
    # /pjt_inventory/27/product_delete
    url(r'^(?P<pk>[0-9]+)/product_delete/$', views.ProductDelete.as_view(), name='product_delete'),
    # /pjt_inventory/supplier_add
    url(r'^supplier_add/$', views.SupplierCreate.as_view(), name='supplier_add'),
    # /pjt_inventory/27/supplier_edit
    url(r'^(?P<pk>[0-9]+)/supplier_edit/$', views.SupplierEdit.as_view(), name='supplier_edit'),
    # /pjt_inventory/27/supplier_delete
    url(r'^(?P<pk>[0-9]+)/supplier_delete/$', views.SupplierDelete.as_view(), name='supplier_delete'),
    # /pjt_inventory/brand_add
    url(r'^brand_add/$', views.BrandCreate.as_view(), name='brand_add'),
    # /pjt_inventory/27/brand_edit
    url(r'^(?P<pk>[0-9]+)/brand_edit/$', views.BrandEdit.as_view(), name='brand_edit'),
    # /pjt_inventory/27/brand_delete
    url(r'^(?P<pk>[0-9]+)/brand_delete/$', views.BrandDelete.as_view(), name='brand_delete'),
    # List pjt_inventory/supplier_contact_list
    url(r'^(?P<pk>[0-9]+)/supplier_contact_list', views.SupplierContactListView.as_view(), name='supplier_contact_list'),
    # /pjt_inventory/supplier_contact_add
    url(r'^supplier_contact_add/$', views.SupplierContactCreate.as_view(), name='supplier_contact_add'),
    # /pjt_inventory/27/supplier_contact_edit
    url(r'^(?P<pk>[0-9]+)/supplier_contact_edit/$', views.SupplierContactEdit.as_view(), name='supplier_contact_edit'),
    # List pjt_inventory/27/category_sub_list
    url(r'^(?P<pk>[0-9]+)/category_sub_list', views.CategorySubListView.as_view(), name='category_sub_list'),
    # /pjt_inventory/category_add
    url(r'^category_add/$', views.CategoryCreate.as_view(), name='category_add'),
    # List pjt_inventory/27/category_product
    url(r'^(?P<pk>[0-9]+)/category_product', views.CategoryProductListView.as_view(), name='category_product'),
    # /pjt_inventory/27/category_edit
    url(r'^(?P<pk>[0-9]+)/category_edit/$', views.CategoryEdit.as_view(), name='category_edit'),
]

pjt_inventory/forms.py
from django import forms
from django.utils import timezone
from datetime import date
from django.contrib.auth.models import User
from .models import Product, Supplier, Brand, SupplierContact, CategoryDescription, Category

class ProductForm(forms.ModelForm):
    #pub_date = forms.DateField(initial=timezone.now())
    #end_date = forms.DateField(initial=timezone.now() + timezone.timedelta(days=1))
    class Meta:
        model = Product
        exclude = ('id',)
        fields = ['barcode','name','brand','supplier','category','size_flag','price_cost','price_bought','price_wholesale','price_retail',
                  'free_shipping','order_min','order_max','desc_header','desc_body','image','remarks','tags','status','date_publish']

    def clean(self):
        cleaned_data = super(ProductForm, self).clean()
        return cleaned_data
        # pub_date = cleaned_data.get('pub_date')
        # end_date = cleaned_data.get('end_date')
        # if pub_date and end_date:
        #     if pub_date < date.today() or end_date <= date.today():
        #         msg = "Date cannot be in the past!"
        #         self.add_error('pub_date', msg)
        #         self.add_error('end_date', msg)
        #     elif end_date <= pub_date:
        #         msg = "End Date cannot be older or same than the opening date.."
        #         self.add_error('end_date', msg)

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        widgets = {
            'is_active': forms.RadioSelect
        }
        exclude = ('id',)
        fields = ['name','desc','tax_num','phone','fax','email','address','city','state','country','zipcode','image','url','tags','is_active']

    def clean(self):
        cleaned_data = super(SupplierForm, self).clean()
        return cleaned_data

class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        widgets = {
            'is_active': forms.RadioSelect
        }
        exclude = ('id',)
        fields = ['name','desc','image','url','tags','is_active']

    def clean(self):
        cleaned_data = super(BrandForm, self).clean()
        return cleaned_data

class SupplierContactForm(forms.ModelForm):
    class Meta:
        model = SupplierContact
        exclude = ('id',)
        fields = ['first_name','last_name','supplier','email','phone','fax','mobile','dept','notes']

    def clean(self):
        cleaned_data = super(SupplierContactForm, self).clean()
        return cleaned_data

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('id',)
        #fields = ['categories_name','categories_description','tags','date_created','date_updated','modified_by']
        fields = ['name', 'description', 'is_child', 'parent', 'image', 'tags']

    def clean(self):
        cleaned_data = super(CategoryForm, self).clean()
        return cleaned_data

pjt_inventory/views.py
#from django.shortcuts import render
#from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .forms import ProductForm, SupplierForm, BrandForm, SupplierContactForm, CategoryForm
from .models import Product, Supplier, Brand, SupplierContact, CategoryDescription, Category

class IndexView(TemplateView):
    template_name = "pjt_inventory/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest_product'] = Product.objects.all()[:1]
        return context

'''
    PRODUCTS
'''
class ProductListView(ListView):
    template_name = 'pjt_inventory/product_list.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.all()


class ProductDetailView(DetailView):
    model = Product
    template_name = 'pjt_inventory/product_detail.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'pjt_inventory/product_detail.html'


class ProductCreate(CreateView):
    model = Product
    template_name = 'pjt_inventory/product_add.html'
    form_class = ProductForm
    success_url = reverse_lazy('pjt_inventory:product_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(ProductCreate, self).form_valid(form)
        else:
            form = ProductForm()
            return render(self, 'pjt_inventory/product_add.html', {'form': form})


class ProductEdit(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'pjt_inventory/product_edit.html'
    success_url = reverse_lazy('pjt_inventory:product_list')

    def form_valid(self, form_class):
        if form_class.is_valid():
            form_class.save()
            instance = form_class.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(ProductEdit, self).form_valid(form_class)
        else:
            form = ProductForm()
            return render(self, 'pjt_inventory/product_edit.html', {'form': form})


class ProductDelete(DeleteView):
    model = Product
    template_name = 'pjt_inventory/product_delete.html'
    success_url = reverse_lazy('pjt_inventory:index')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

'''
    SUPPLIERS
'''
class SupplierListView(ListView):
    template_name = 'pjt_inventory/supplier_list.html'
    context_object_name = 'supplier_list'

    def get_queryset(self):
        return Supplier.objects.all()


class SupplierDetailView(DetailView):
    model = Supplier
    template_name = 'pjt_inventory/supplier_detail.html'


class SupplierEdit(UpdateView):
    model = Supplier
    template_name = 'pjt_inventory/supplier_edit.html'
    form_class = SupplierForm
    success_url = reverse_lazy('pjt_inventory:supplier_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(SupplierEdit, self).form_valid(form)
        else:
            form = SupplierForm()
            return render(self, 'pjt_inventory/supplier_edit.html', {'form': form})


class SupplierDelete(DeleteView):
    model = Supplier
    template_name = 'pjt_inventory/supplier_delete.html'
    success_url = reverse_lazy('pjt_inventory:supplier_list')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)


class SupplierCreate(CreateView):
    model = Supplier
    template_name = 'pjt_inventory/supplier_add.html'
    form_class = SupplierForm
    success_url = reverse_lazy('pjt_inventory:supplier_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(SupplierCreate, self).form_valid(form)
        else:
            form = SupplierForm()
            return render(self, 'pjt_inventory/supplier_add.html', {'form': form})

'''
    SUPPLIER CONTACTS
'''
class SupplierContactListView(ListView):
    template_name = 'pjt_inventory/supplier_contact_list.html'
    context_object_name = 'supplier_contact_list'

    def get_queryset(self):
        supplier = Supplier.objects.get(pk=self.kwargs.get('pk'))
        return supplier.supplier_contacts.all()


class SupplierContactCreate(CreateView):
    model = SupplierContact
    template_name = 'pjt_inventory/supplier_contact_add.html'
    form_class = SupplierContactForm
    success_url = reverse_lazy('pjt_inventory:supplier_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(SupplierContactCreate, self).form_valid(form)
        else:
            form = SupplierContactForm()
            return render(self, 'pjt_inventory/supplier_contact_add.html', {'form': form})


class SupplierContactEdit(UpdateView):
    model = SupplierContact
    template_name = 'pjt_inventory/supplier_contact_edit.html'
    form_class = SupplierContactForm
    success_url = reverse_lazy('pjt_inventory:supplier_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(SupplierContactEdit, self).form_valid(form)
        else:
            form = SupplierContactForm()
            return render(self, 'pjt_inventory/supplier_contact_edit.html', {'form': form})

'''
    BRANDS
'''
class BrandListView(ListView):
    template_name = 'pjt_inventory/brand_list.html'
    context_object_name = 'brand_list'

    def get_queryset(self):
        return Brand.objects.all()


class BrandDetailView(DetailView):
    model = Brand
    template_name = 'pjt_inventory/brand_detail.html'


class BrandCreate(CreateView):
    model = Brand
    template_name = 'pjt_inventory/brand_add.html'
    form_class = BrandForm
    success_url = reverse_lazy('pjt_inventory:brand_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(BrandCreate, self).form_valid(form)
        else:
            form = BrandForm()
            return render(self, 'pjt_inventory/brand_add.html', {'form': form})


class BrandEdit(UpdateView):
    model = Brand
    template_name = 'pjt_inventory/brand_edit.html'
    form_class = BrandForm
    success_url = reverse_lazy('pjt_inventory:brand_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()
            return super(BrandEdit, self).form_valid(form)
        else:
            form = BrandForm()
            return render(self, 'pjt_inventory/brand_edit.html', {'form': form})


class BrandDelete(DeleteView):
    model = Brand
    template_name = 'pjt_inventory/brand_delete.html'
    success_url = reverse_lazy('pjt_inventory:brand_list')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

'''
    CATEGORY
'''

class CategoryListView(ListView):
    template_name = 'pjt_inventory/category_list.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        #return Category.objects.filter(is_child=False).exclude(id=11)
        return Category.objects.filter(parent_id=11).exclude(id=11)


class CategorySubListView(ListView):
    template_name = 'pjt_inventory/category_sub_list.html'
    context_object_name = 'category_sub_list'

    def get_queryset(self):
        return Category.objects.filter(parent_id=self.kwargs.get('pk'))

    def get_context_data(self, *args, **kwargs):
        context = super(CategorySubListView, self).get_context_data(*args, **kwargs)
        context['category_products'] = Product.objects.filter(category=self.kwargs.get('pk'))
        return context


class CategoryProductListView(ListView):
    template_name = 'pjt_inventory/category_product.html'
    context_object_name = 'category_products'

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs.get('pk'))

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryProductListView, self).get_context_data(*args, **kwargs)
        context['category_sub_list'] = Category.objects.filter(parent_id=self.kwargs.get('pk'))
        return context


class CategoryCreate(CreateView):
    model = Category
    template_name = 'pjt_inventory/category_add.html'
    form_class = CategoryForm
    success_url = reverse_lazy('pjt_inventory:category_list')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            instance = form.instance
            instance.modified_by = self.request.user
            instance.save()

pjt_inventory/templates/pjt_inventory/brand_add.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}

<h3>Add Brand</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="submit-link-row">{{ field.label_tag }} {{ field }}
        {% if form.errors %}
            {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
            {% endfor %}
        {% endif %}
        </div>
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    {% endfor %}
    <input type="submit" value="Add" />
</form>


{% if error_message3 %}
    <p>
        <strong>{{ error_message3 }}</strong>
    </p>
{% endif %}
<a class="body" href="{% url 'pjt_inventory:brand_list' %}">Cancel</a>
<t />
<a class="body" href="{% url 'pjt_inventory:index' %}">Home</a>
{% endblock %}

pjt_inventory/templates/pjt_inventory/brand_edit.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}

<h3>Edit Brand</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="submit-link-row">{{ field.label_tag }} {{ field }}
        {% if form.errors %}
            {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
            {% endfor %}
        {% endif %}
        </div>
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    {% endfor %}
    <input type="submit" value="Update" />
</form>


{% if error_message3 %}
    <p>
        <strong>{{ error_message3 }}</strong>
    </p>
{% endif %}
<a class="body" href="{% url 'pjt_inventory:brand_list' %}">Cancel</a>
{% endblock %}

pjt_inventory/templates/pjt_inventory/brand_list.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}
<a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:brand_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
<br />
{% if brand_list %}
<ul>
    {% for brand in brand_list %}
        <li><a href="{% url 'pjt_inventory:brand_detail' brand.id %}">{{ brand.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No brands are available.</p>
{% endif %}
{% endblock content %}

pjt_inventory/templates/pjt_inventory/category_list.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}
<a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:category_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
<br />
{% if category_list %}
<ul>
    {% for category in category_list %}
        <li>
            <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:category_edit' category.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="{% url 'pjt_inventory:category_sub_list' category.id %}">{{ category.name }}</a>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>No Category available.</p>
{% endif %}
{% endblock content %}

pjt_inventory/templates/pjt_inventory/detail.html
{% extends 'pjt_inventory/base.html' %}
{% load pjt_inventory_tags %}

{% block content %}
<h1>{{ product.name }}
    <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:product_edit' product.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:product_delete' product.id %}"><span class="glyphicon glyphicon-trash"></span></a>
</h1>

    <table>
        <tr>
            <th>Properties:</th>
            <th>Value:</th>
        </tr>
    {% for name, value in product.get_fields %}
        {% if value %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ value | get_format }}</td>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
    <br />
<a class="body" href="{% url 'pjt_inventory:index' %}">Home</a>
{% endblock content %}

pjt_inventory/templates/pjt_inventory/product_add.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}

<h3>Add Product</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="submit-link-row">
            {{ field.label_tag }} {{ field }}
            {% if field.name == 'brand' %}
                <a target="_blank" class="btn btn-default btn-sm" href="{% url 'pjt_inventory:brand_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            {% if field.name == 'supplier' %}
                <a target="_blank" class="btn btn-default btn-sm" href="{% url 'pjt_inventory:supplier_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            {% if field.name == 'category' %}
                <a target="_blank" class="btn btn-default btn-sm" href="{% url 'pjt_inventory:category_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
        {% if form.errors %}
            {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
            {% endfor %}
        {% endif %}
        </div>

        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    {% endfor %}
    <input type="submit" value="Add" />
</form>


{% if error_message3 %}
    <p>
        <strong>{{ error_message3 }}</strong>
    </p>
{% endif %}
<a class="body" href="{% url 'pjt_inventory:product_list' %}">Cancel</a>
<t />
<a class="body" href="{% url 'pjt_inventory:index' %}">Home</a>
{% endblock %}

pjt_inventory/templates/pjt_inventory/product_delete.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}

<h3>Delete Product</h3>

<form action="" method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete Product "{{ object }}"?</h3>
    <input type="submit" value="Yes" />
</form>


{% if error_message3 %}
    <p>
        <strong>{{ error_message3 }}</strong>
    </p>
{% endif %}
<a class="body" href="{% url 'pjt_inventory:index' %}">Cancel</a>
{% endblock %}

pjt_inventory/templates/pjt_inventory/product_detail.html
{% extends 'pjt_inventory/base.html' %}
{% load pjt_inventory_tags %}

{% block content %}
<h3>{{ product.name }}
    <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:product_edit' product.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:product_delete' product.id %}"><span class="glyphicon glyphicon-trash"></span></a>
</h3>

    <table>
        <tr>
            <th>Properties:</th>
            <th>Value:</th>
        </tr>
        <tr>
            <td> Barcode: </td>
            <td> {{ product.barcode }} </td>
        </tr>
        <tr>
            <td> Product Name: </td>
            <td> {{ product.name }} </td>
        </tr>
        <tr>
            <td>  Brand: </td>
            <td> {{ product.brand }} </td>
        </tr>
        <tr>
            <td> Supplier: </td>
            <td> {{ product.supplier }} </td>
        </tr>
        <tr>
            <td> Category: </td>
            <td> {{ product.category }} </td>
        </tr>
        <tr>
            <td> Size: </td>
            <td> {{ product.size_flag }} </td>
        </tr>
        <tr>
            <td> Price Cost: </td>
            <td> {{ product.price_cost }} </td>
        </tr>
        <tr>
            <td> Price Bought: </td>
            <td> {{ product.price_bought }} </td>
        </tr>
        <tr>
            <td>  Wholesale Price: </td>
            <td> {{ product.price_wholesale }} </td>
        </tr>
        <tr>
            <td> Retail Price: </td>
            <td> {{ product.price_retail }} </td>
        </tr>
        <tr>
            <td> Shipping: </td>
            <td> {{ product.free_shipping }} </td>
        </tr>
        <tr>
            <td> Minimum order: </td>
            <td> {{ product.order_min }} </td>
        </tr>
        <tr>
            <td> Maximum order: </td>
            <td> {{ product.order_max }} </td>
        </tr>
        <tr>
            <td> Description Header: </td>
            <td> {{ product.desc_header }} </td>
        </tr>
        <tr>
            <td> Description: </td>
            <td> {{ product.desc_body }} </td>
        </tr>
        <tr>
            <td> Status: </td>
            <td> {{ product.status }} </td>
        </tr>
        <tr>
            <td> Image: </td>
            <td> {{ product.image }} </td>
        </tr>
        <tr>
            <td> Remarks: </td>
            <td> {{ product.remarks }} </td>
        </tr>
        <tr>
            <td> Tags: </td>
            <td> {{ product.tags }} </td>
        </tr>
        <tr>
            <td> Date Created: </td>
            <td> {{ product.date_created | date:"M d, Y" }} </td>
        </tr>
        <tr>
            <td> Date Updated: </td>
            <td> {{ product.date_updated | date:"M d, Y" }} </td>
        </tr>
        <tr>
            <td> Date Published: </td>
            <td> {{ product.date_publish | date:"M d, Y" }} </td>
        </tr>
        <tr>
            <td> Modified By: </td>
            <td> {{ product.modified_by }} </td>
        </tr>
    </table>
    <br />
<a class="body" href="{% url 'pjt_inventory:product_list' %}">Back</a>
<a class="body" href="{% url 'pjt_inventory:index' %}">Home</a>
{% endblock content %}

pjt_inventory/templates/pjt_inventory/product_list.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}
<a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:product_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
<br />
{% if product_list %}
<ul>
    {% for product in product_list %}
        <li><a href="{% url 'pjt_inventory:product_detail' product.id %}">{{ product.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No products are available.</p>
{% endif %}
{% endblock content %}

pjt_inventory/templates/pjt_inventory/supplier_contact_list.html
{% extends 'pjt_inventory/base.html' %}
{% load pjt_inventory_tags %}

{% block content %}
<a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:supplier_contact_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
<br />
{% if supplier_contact_list %}
    {% for contact in supplier_contact_list %}
        <h3>
            {{ contact.first_name }} {{ contact.last_name }}
            <a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:supplier_contact_edit' contact.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
        </h3>
        <ul>
            <li>Email:		{{ contact.email }} </li>
            <li>Phone No.:	{{ contact.phone }} </li>
            <li>Fax No.:	{{ contact.fax }} </li>
            <li>Mobile: 	{{ contact.mobile }} </li>
            <li>Department: {{ contact.dept }} </li>
            <li>Notes:		{{ contact.notes }} </li>
            <li>Date Added:	{{ contact.date_created }} </li>
            <li>Date Updated:	{{ contact.date_updated }} </li>
            <li>Modified by:	{{ contact.modified_by }} </li>
         </ul>
        <hr>
    {% endfor %}
{% else %}
    <p>No supplier contacts available.</p>
{% endif %}
<a class="body" href="{% url 'pjt_inventory:supplier_list' %}">Back</a>
<a class="body" href="{% url 'pjt_inventory:index' %}">Home</a>
{% endblock content %}

pjt_inventory/templates/pjt_inventory/supplier_list.html
{% extends 'pjt_inventory/base.html' %}

{% block content %}
<a class="btn btn-default btn-sm" href="{% url 'pjt_inventory:supplier_add' %}"><span class="glyphicon glyphicon-plus"></span></a>
<br />
{% if supplier_list %}
<ul>
    {% for supplier in supplier_list %}
        <li><a href="{% url 'pjt_inventory:supplier_detail' supplier.id %}">{{ supplier.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No supplier are available.</p>
{% endif %}
{% endblock content %}